In [1]:
# Import 

import torch
import numpy as np

In [4]:
# We can create a tensor from given data. 

data = [[2,4],[3,5]]
x_data = torch.tensor(data)

In [3]:
# We can convert numpy arrays into tensors as well. 

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
# We can take the shape of the data that we created and use the information to create tensors with given properties of interest.

x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
# We can define the shape of the tensor we want a create a specific tensor.

shape = (3,4,)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.2510, 0.2578, 0.5619, 0.1075],
        [0.4771, 0.9347, 0.0193, 0.9917],
        [0.5061, 0.0890, 0.0869, 0.5991]])

In [17]:
# Printing out some attributes of tensors. 

print('The size of the tensor -->',rand_tensor.shape,'\nThe data type of the tensor -->',rand_tensor.dtype,'\nWhere is it stored -->',rand_tensor.device)

The size of the tensor --> torch.Size([3, 4]) 
The data type of the tensor --> torch.float32 
Where is it stored --> cpu


In [18]:
# We can glue together tensors together. 

t1 = torch.cat([rand_tensor, rand_tensor, rand_tensor], dim=1)
print(t1)

tensor([[0.2510, 0.2578, 0.5619, 0.1075, 0.2510, 0.2578, 0.5619, 0.1075, 0.2510,
         0.2578, 0.5619, 0.1075],
        [0.4771, 0.9347, 0.0193, 0.9917, 0.4771, 0.9347, 0.0193, 0.9917, 0.4771,
         0.9347, 0.0193, 0.9917],
        [0.5061, 0.0890, 0.0869, 0.5991, 0.5061, 0.0890, 0.0869, 0.5991, 0.5061,
         0.0890, 0.0869, 0.5991]])


In [21]:
# Multiplying two tensors. 

y2 = rand_tensor.matmul(rand_tensor.T)
y2

tensor([[0.4567, 0.4781, 0.2632],
        [0.4781, 2.0851, 0.9204],
        [0.2632, 0.9204, 0.6306]])

# Completes the Tutorial